version: "3"

services:

  data-challenge-database:
    build: .
    container_name: data-challenge-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      data-challenge-network:
        aliases:
          - data.challenge.database

networks:
  data-challenge-network:
    external: true